# Generated by Django 4.1.7 on 2023-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Client')], default='SERVER', max_length=6, null=True),
        ),
    ]
