# Generated by Django 4.1.7 on 2023-06-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender_type',
        ),
    ]
