# Generated by Django 4.1.7 on 2023-07-05 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='chat',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
