# Generated by Django 4.1.7 on 2023-06-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Client')], default='SERVER', max_length=6, null=True),
        ),
    ]
