# Generated by Django 4.1.7 on 2023-05-02 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_publicroomchatmessage_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicChatRoom',
            new_name='ChatRoom',
        ),
    ]
