# Generated by Django 4.1.7 on 2023-07-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_chat_reciever_chat_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='chat',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats_reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
