# Generated by Django 4.1.7 on 2023-07-05 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_chat_customer_remove_chat_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
