# Generated by Django 4.1.7 on 2023-03-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('purches_counts', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('drink', 'Drink'), ('iranian_food', 'Iranian_food'), ('foreign_food', 'Foreign_food')], max_length=255)),
                ('restaurants', models.ManyToManyField(related_name='food', to='Restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Specifics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ingredients', models.CharField(max_length=1024, null=True)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.food')),
                ('ResID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
            ],
            options={
                'unique_together': {('FoodID', 'ResID')},
            },
        ),
    ]
