# Generated by Django 4.1.7 on 2023-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="food_pic",
            field=models.ImageField(blank=True, null=True, upload_to="Food_pics/"),
        ),
    ]
