# Generated by Django 4.1.7 on 2023-04-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_restaurant_logo'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Food_pics/'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='User.restaurant'),
            preserve_default=False,
        ),
    ]
