# Generated by Django 4.1.7 on 2023-05-25 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
