# Generated by Django 4.1.7 on 2023-03-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="Name",
            new_name="name",
        ),
    ]
