# Generated by Django 4.1.7 on 2023-05-25 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(default=datetime.date(2023, 5, 25)),
        ),
    ]
