# Generated by Django 4.1.7 on 2023-04-11 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_rename_name_food_name_rename_name_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='food',
            name='Food_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Food_pics/'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='1234', max_length=8, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vc_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Type',
            field=models.CharField(blank=True, choices=[('drink', 'Drink'), ('iranian_food', 'Iranian_food'), ('foreign_food', 'Foreign_food')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Food_Specifics',
        ),
    ]
