# Generated by Django 4.1.7 on 2023-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, choices=[('Drink', 'Drink'), ('Iranian', 'Iranian'), ('Foreign', 'Foreign')], max_length=255),
        ),
    ]
