# Generated by Django 4.1.7 on 2023-04-10 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0002_rename_name_food_name_rename_name_restaurant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="password",
            field=models.CharField(
                max_length=8,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vc_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
