# Generated by Django 4.1.7 on 2023-05-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_restaurant_date_of_establishment'),
        ('Restaurant', '0003_alter_food_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('userId', 'restaurant')},
        ),
    ]
