# Generated by Django 4.1.7 on 2023-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0003_restaurant_email_confirmed_restaurant_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
    ]
