# Generated by Django 4.1.7 on 2023-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Cancled', 'Cancled'), ('Ordered', 'Ordered'), ('notOrdered', 'notOrdered')], default='notOrdered', max_length=255),
        ),
    ]
