# Generated by Django 4.1.7 on 2023-04-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0005_alter_restaurant_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="email_confirmed",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="vc_code",
        ),
    ]
