# Generated by Django 4.1.7 on 2023-04-10 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Restaurant", "0003_restaurant_email_confirmed_restaurant_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("role", models.CharField(default="Customer", max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "username",
                    models.CharField(
                        default=models.CharField(max_length=255), max_length=255
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_confirmed", models.BooleanField(default=False)),
                ("vc_code", models.CharField(max_length=6, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "09123456789". Up to 15 digits allowed.',
                                regex="^09\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=255,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "password",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                (
                    "wallet_balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, null=True
                    ),
                ),
                (
                    "list_of_favorites_res",
                    models.ManyToManyField(
                        related_name="cust_favor_list", to="Restaurant.restaurant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
