# Generated by Django 4.1.7 on 2023-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='list_of_favorites_res',
            field=models.ManyToManyField(blank=True, null=True, related_name='cust_favor_list', to='User.restaurant'),
        ),
    ]
