# Generated by Django 4.1.7 on 2023-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
    ]
