# Generated by Django 4.1.7 on 2023-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="lat",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="lon",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
