# Generated by Django 4.1.7 on 2023-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauthor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
