# Generated by Django 4.1.7 on 2023-04-17 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_restaurant_date_of_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
    ]
