# Generated by Django 4.1.7 on 2023-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(default="Customer", max_length=255),
        ),
    ]
