# Generated by Django 4.1.7 on 2023-03-29 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='userName',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "09123456789". Up to 15 digits allowed.', regex='^09\\d{9}$')]),
        ),
    ]
