# Generated by Django 4.1.7 on 2023-04-15 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myauthor",
            name="password",
            field=models.CharField(
                max_length=16, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
    ]
