# Generated by Django 4.1.7 on 2023-06-07 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_restaurant_lat_restaurant_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
    ]
