# Generated by Django 4.1.7 on 2023-04-16 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_myauthor_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="count_rates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="rate",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
