# Generated by Django 4.1.7 on 2023-04-11 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_customer_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="VC_Codes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("vc_code", models.CharField(max_length=6, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                max_length=16, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
    ]
