# Generated by Django 4.1.7 on 2023-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_restaurant_date_of_establishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
