# Generated by Django 4.1.7 on 2023-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_restaurant_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="email_confirmed",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="vc_code",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="purches_counts",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
