# Generated by Django 4.1.7 on 2023-05-17 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_restaurant_date_of_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 5, 18)),
        ),
    ]
