# Generated by Django 4.1.7 on 2023-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_customer_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="Name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="userName",
            field=models.CharField(
                default=models.CharField(max_length=255), max_length=255
            ),
        ),
    ]
