# Generated by Django 4.1.7 on 2023-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_myauthor_address_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
