# Generated by Django 4.1.7 on 2023-03-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_customer_username_alter_customer_address_and_more'),
        ('User', '0003_rename_first_name_customer_name_and_more'),
    ]

    operations = [
    ]
