# Generated by Django 4.1.7 on 2023-04-05 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "09123456789". Up to 15 digits allowed.', regex='^09\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='vc_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
