# Generated by Django 4.1.7 on 2023-03-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customer_date_joined_customer_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
    ]
