# Generated by Django 4.1.7 on 2023-05-17 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customer_customer_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 5, 17)),
        ),
    ]
