# Generated by Django 4.1.7 on 2023-04-16 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_restaurant_count_rates_restaurant_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rate",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
