# Generated by Django 4.1.7 on 2023-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_restaurant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
