# Generated by Django 4.1.7 on 2023-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_merge_20230330_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userName',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
