# Generated by Django 4.1.7 on 2023-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_customer_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="userName",
            new_name="username",
        ),
        migrations.AddField(
            model_name="customer",
            name="vc_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
