# Generated by Django 4.1.7 on 2023-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customer_address_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
