# Generated by Django 4.1.7 on 2023-05-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_restaurant_date_of_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='purches_counts',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
