# Generated by Django 4.1.7 on 2023-04-01 09:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0006_rename_name_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalaxyUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(max_length=765)),
                ("password", models.CharField(max_length=120)),
                ("external", models.IntegerField(blank=True, null=True)),
                ("deleted", models.IntegerField(blank=True, null=True)),
                ("purged", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=765)),
                ("form_values_id", models.IntegerField(blank=True, null=True)),
                (
                    "disk_usage",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=16, null=True
                    ),
                ),
            ],
            options={
                "db_table": "galaxy_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
