# Generated by Django 4.1.7 on 2023-05-23 08:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_alter_restaurant_purches_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="count_rates",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="date_of_establishment",
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rate",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
