# Generated by Django 4.1.7 on 2023-04-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_galaxyuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalaxyUser",
        ),
    ]
