# Generated by Django 4.1.7 on 2023-05-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_restaurant_date_of_establishment'),
        ('User', '0007_alter_restaurant_purches_counts'),
    ]

    operations = [
    ]
