# Generated by Django 4.1.7 on 2023-04-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_restaurant_rate'),
        ('User', '0007_restaurant_logo'),
    ]

    operations = [
    ]
