# Generated by Django 4.1.7 on 2023-05-19 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_merge_20230519_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
    ]
