# Generated by Django 4.1.7 on 2023-05-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_restaurant_count_rates_alter_restaurant_rate'),
        ('User', '0009_alter_restaurant_date_of_establishment'),
    ]

    operations = [
    ]
